# Generated by Django 2.1.1 on 2018-10-01 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dance-single', 'Dance single'), ('dance-double', 'Dance double')], max_length=50)),
                ('meter', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Novice', 'Novice'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert'), ('Edit', 'Edit')], max_length=50)),
                ('taps', models.IntegerField()),
                ('jumps', models.IntegerField()),
                ('hands', models.IntegerField()),
                ('holds', models.IntegerField()),
                ('rolls', models.IntegerField()),
                ('mines', models.IntegerField()),
                ('lifts', models.IntegerField()),
                ('fakes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('anime', 'Anime'), ('chiptune', 'Chiptune'), ('dnb', 'Drum and Bass'), ('electronic', 'Electronic'), ('happy_hardcore', 'Happy Hardcore'), ('hardcore', 'Hardcore (Gabber)'), ('pop', 'Pop'), ('hiphop', 'Rap/Hip Hop'), ('rock', 'Rock/Metal'), ('videogame', 'Video Game'), ('other', 'Other'), ('unknown', 'Not Specified')], default=('unknown', 'Not Specified'), max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('has_stops', models.BooleanField(default=False)),
                ('bpm_type', models.CharField(choices=[('fixed', 'Fixed'), ('random', 'Random'), ('varies', 'Varies')], max_length=50)),
                ('min_bpm', models.FloatField(default=60.0)),
                ('max_bpm', models.FloatField(default=60.0)),
                ('banner_url', models.CharField(max_length=255)),
                ('download_url', models.CharField(max_length=255)),
                ('preview_url', models.CharField(max_length=255)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
