# Generated by Django 2.1.1 on 2018-10-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20181001_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='song.Song'),
        ),
    ]
