# Generated by Django 2.1.2 on 2018-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20181001_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='banner_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
