# Generated by Django 2.1.2 on 2018-12-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20181005_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
