# Generated by Django 2.1.1 on 2018-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180928_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(error_messages={'unique': 'A user with that username already exists.'}, max_length=20, unique=True, verbose_name='username'),
        ),
    ]
